from django.urls import include,path
from django.contrib import admin

from . import views

app_name = 'keypadcodes'

urlpatterns = [
    path('', views.IndexView, name='index'),
    path('people/', views.PeopleView, name='people'),
    path('person/<int:person_id>/', views.person, name='person'),
    # path('person/<int:pk>/update/', views.personUpdateiew.as_view(), name='person-update'),
    path('person/update/<int:person_id>', views.updatePerson, name='person-update'),
    path('person/create/', views.PersonCreateView.as_view(), name='person-create'),
    path('personaddress/create/<int:person_id>', views.createAddress, name='personaddress-create'),
    path('personaddress/delete/<int:address_id>', views.deleteAddress, name='personaddress-delete'),
    path('personaddress/update/<int:address_id>', views.updateAddress, name='personaddress-update'),
    path('personadvisor/create/<int:person_id>', views.createAdvisor, name='personadvisor-create'),
    path('personadvisor/delete/<int:advisor_id>', views.deleteAdvisor, name='personadvisor-delete'),
    path('personadvisor/update/<int:advisor_id>', views.updateAdvisor, name='personadvisor-update'),
    path('personadvisee/create/<int:person_id>', views.createAdvisee, name='personadvisee-create'),
    path('personadvisee/delete/<int:advisee_id>', views.deleteAdvisee, name='personadvisee-delete'),
    path('personadvisee/update/<int:advisee_id>', views.updateAdvisee, name='personadvisee-update'),
    path('personaffiliatedorganization/create/<int:person_id>', views.createAffiliatedOrganization, name='personaffiliatedorganization-create'),
    path('personaffiliatedorganization/delete/<int:affiliatedorganization_id>', views.deleteAffiliatedOrganization, name='personaffiliatedorganization-delete'),
    path('personaffiliatedorganization/update/<int:affiliatedorganization_id>', views.updateAffiliatedOrganization, name='personaffiliatedorganization-update'),
    path('personapplication/create/<int:person_id>', views.createApplication, name='personapplication-create'),
    path('personapplication/delete/<int:application_id>', views.deleteApplication, name='personapplication-delete'),
    path('personapplication/update/<int:application_id>', views.updateApplication, name='personapplication-update'),
    path('personbiologydegreearea/create/<int:person_id>/', views.createBiologyDegreeArea, name='personbiologydegreearea-create'),
    path('personbiologydegreearea/delete/<int:biologydegreearea_id>', views.deleteBiologyDegreeArea, name='personbiologydegreearea-delete'),
    path('personbiologydegreearea/update/<int:biologydegreearea_id>', views.updateBiologyDegreeArea, name='personbiologydegreearea-update'),
    path('personbiologydeptjobtitle/create/<int:person_id>/', views.createBiologyDeptJobTitle, name='personbiologydeptjobtitle-create'),
    path('personbiologydeptjobtitle/delete/<int:biologydeptjobtitle_id>/', views.deleteBiologyDeptJobTitle, name='personbiologydeptjobtitle-delete'),
    path('personbiologydeptjobtitle/update/<int:biologydeptjobtitle_id>', views.updateBiologyDeptJobTitle, name='personbiologydeptjobtitle-update'),
    path('personcommitteeassignment/create/<int:person_id>/', views.createCommitteeAssignment, name='personcommitteeassignment-create'),
    path('personcommitteeassignment/delete/<int:committeeassignment_id>/', views.deleteCommitteeAssignment, name='personcommitteeassignment-delete'),
    path('personcommitteeassignment/update/<int:committeeassignment_id>', views.updateCommitteeAssignment, name='personcommitteeassignment-update'),
    path('personeducation/create/<int:person_id>/', views.createEducation, name='personeducation-create'),
    path('personeducation/delete/<int:education_id>/', views.deleteEducation, name='personeducation-delete'),
    path('personeducation/update/<int:education_id>', views.updateEducation, name='personeducation-update'),
    path('personemailaddress/create/<int:person_id>/', views.createEmailAddress, name='personemailaddress-create'),
    path('personemailaddress/delete/<int:emailaddress_id>/', views.deleteEmailaddress, name='personemailaddress-delete'),
    path('personemailaddress/update/<int:emailaddress_id>', views.updateEmailaddress, name='personemailaddress-update'),
    path('personkeypadcode/create/<int:person_id>/', views.createKeypadcode, name='personkeypadcode-create'),
    path('personkeypadcode/delete/<int:keypadcode_id>/', views.deleteKeypadcode, name='personkeypadcode-delete'),
    path('personkeypadcode/update/<int:keypadcode_id>', views.updateKeypadcode, name='personkeypadcode-update'),
    path('personlab/create/<int:person_id>/', views.createLab, name='personlab-create'),
    path('personlab/delete/<int:lab_id>/', views.deleteLab, name='personlab-delete'),
    path('personlab/update/<int:lab_id>', views.updateLab, name='personlab-update'),
    path('personlistserv/create/<int:person_id>/', views.createListserv, name='personlistserv-create'),
    path('personlistserv/delete/<int:listserv_id>/', views.deleteListserv, name='personlistserv-delete'),
    path('personlistserv/update/<int:listserv_id>', views.updateListserv, name='personlistserv-update'),
    path('personofficehours/create/<int:person_id>/', views.createOfficeHours, name='personofficehours-create'),
    path('personofficehours/delete/<int:officehours_id>/', views.deleteOfficeHours, name='personofficehours-delete'),
    path('personofficehours/update/<int:officehours_id>/', views.updateOfficeHours, name='personofficehours-update'),
    path('personphone/create/<int:person_id>/', views.createPhone, name='personphone-create'),
    path('personphone/delete/<int:phone_id>/', views.deletePhone, name='personphone-delete'),
    path('personphone/update/<int:phone_id>', views.updatePhone, name='personphone-update'),
    path('personpublication/create/<int:person_id>/', views.createPublication, name='personpublication-create'),
    path('personpublication/delete/<int:publication_id>/', views.deletePublication, name='personpublication-delete'),
    path('personpublication/update/<int:publication_id>', views.updatePublication, name='personpublication-update'),
    path('personresearchinfo/create/<int:person_id>/', views.createResearchinfo, name='personresearchinfo-create'),
    path('personresearchinfo/delete/<int:researchinfo_id>/', views.deleteResearchinfo, name='personresearchinfo-delete'),
    path('personresearchinfo/update/<int:researchinfo_id>/', views.updateResearchinfo, name='personresearchinfo-update'),
    path('personroom/create/<int:person_id>/', views.createRoom, name='personroom-create'),
    path('personroom/delete/<int:room_id>/', views.deleteRoom, name='personroom-delete'),
    path('personroom/update/<int:room_id>/', views.updateRoom, name='personroom-update'),
    path('personualbanyidcardgroup/create/<int:person_id>/', views.createUAlbanyIDCardGroup, name='personualbanyidcardgroup-create'),
    path('personualbanyidcardgroup/delete/<int:ualbanyidcardgroup_id>/', views.deleteUAlbanyIDCardGroup, name='personualbanyidcardgroup-delete'),
    path('personualbanyidcardgroup/update/<int:ualbanyidcardgroup_id>/', views.updateUAlbanyIDCardGroup, name='personualbanyidcardgroup-update'),
    path('personwebsite/create/<int:person_id>/', views.createWebsite, name='personwebsite-create'),
    path('personwebsite/delete/<int:website_id>/', views.deleteWebsite, name='personwebsite-delete'),
    path('personwebsite/update/<int:website_id>/', views.updateWebsite, name='personwebsite-update'),
    path('dataentry/', views.dataEntry, name='dataentry'),
    path('reports/', views.reports, name='reports'),
    path('reports/reportview/', views.reportView, name='reportview'),
    ]
